export const LABELS = {
	// time
	year: "y",
	month: "mo",
	week: "wk",
	day: "d",
	hour: "h",
	minute: "min",
	second: "s",
	millisecond: "ms",
	microsecond: "µs",
	nanosecond: "ns",
	picosecond: "ps",
	femtosecond: "fs",
	attosecond: "as",
	zeptosecond: "zs",
	yoctosecond: "ys",

	// length
	meter: "m",
	kilometer: "km",
	centimeter: "cm",
	millimeter: "mm",
	micrometer: "µm",
	nanometer: "nm",
	picometer: "pm",
	femtometer: "fm",
	attometer: "am",
	zeptometer: "zm",
	yoctometer: "ym",
	ronnameter: "Rm",
	quettameter: "Qm",
	inch: "in",
	foot: "ft",
	yard: "yd",
	mile: "mi",
	"nautical mile": "nmi",
	link: "link",
	fathom: "ftm",
	chain: "ch",
	league: "lea",

	// mass
	kilogram: "kg",
	gram: "g",
	milligram: "mg",
	microgram: "µg",
	nanogram: "ng",
	picogram: "pg",
	femtogram: "fg",
	attogram: "ag",
	zeptogram: "zg",
	yoctogram: "yg",
	ronnagram: "Rg",
	quettagram: "Qg",
	tonne: "t",
	"electronvolt per c squared": "eV/c^2",
	pound: "lb",
	ounce: "oz",
	stone: "st",
	"dalton (unified atomic mass unit)": "Da",
	"atomic mass unit": "u",
	carat: "ct",

	// amount of substance
	mole: "mol",

	// electricCurrent
	ampere: "A",
	coulomb: "C",
	volt: "V",
	ohm: "Ω",
	siemens: "S",
	watt: "W",
	farad: "F",
	henry: "H",
	hertz: "Hz",
	joule: "J",

	// thermodynamic temperature
	kelvin: "K",
	celsius: "°C",
	fahrenheit: "°F",
	rankine: "°R",
	delisle: "°De",
	newton: "°N",
	réaumur: "°Ré",
	rømer: "°Rø",

	// luminous intensity
	candela: "cd",
	stilb: "sb",
} as const;
