name: Code quality

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"
  pull_request:
    branches: [main]
    paths:
      - "src/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
