name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.19

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Test package version consistency
        run: bun run convert test:run

      - name: Build
        run: bun run convert build

      - name: "Publish to NPM"
        working-directory: ./packages/unit-conversion
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish --provenance --access=public

      - name: "Publish to JSR"
        working-directory: ./packages/unit-conversion
        run: npx jsr publish
